"""Official trilogy names in every language the Enhanced Editions ship.

``web/catalog_names.json`` is generated by ``tools/build_official_names.py``
from the Enhanced Editions' string tables: release family → kind (items,
upgrades, factions) → section key → {language → name}.  Presentation only;
it never feeds a writer.  Languages the games were not released in (pt_BR,
tr) use the English names.
"""

from __future__ import annotations

import json
from functools import cache
from pathlib import Path
from typing import Literal

from .i18n import current_language

NAMES_PATH = Path(__file__).resolve().parents[1] / "web" / "catalog_names.json"
Kind = Literal["items", "upgrades", "factions"]
_FAMILIES = {"soc", "clear_sky", "cop"}


_installed: dict[str, dict[str, dict[str, dict[str, str]]]] | None = None


def _releases(payload: object) -> dict[str, dict[str, dict[str, dict[str, str]]]]:
    releases = payload.get("releases") if isinstance(payload, dict) else None
    return releases if isinstance(releases, dict) else {}


@cache
def _load(path: str) -> dict[str, dict[str, dict[str, dict[str, str]]]]:
    try:
        return _releases(json.loads(Path(path).read_text(encoding="utf-8")))
    except (OSError, ValueError):
        return {}


def install(payload: str) -> int:
    """Use names fetched by the web page instead of a file on disk."""

    global _installed
    try:
        _installed = _releases(json.loads(payload))
    except ValueError:
        _installed = {}
    return sum(len(tables.get("items", {})) for tables in _installed.values())


def release_family(release_id: str | None) -> str | None:
    value = str(release_id or "").casefold()
    if value.startswith("stalker2"):
        return None
    if "cop" in value or "pripyat" in value or "prypiat" in value:
        return "cop"
    if "-cs" in value or "clear" in value or value == "cs":
        return "clear_sky"
    if "soc" in value or "shadow" in value:
        return "soc"
    return value if value in _FAMILIES else None


def official_name(
    release_id: str | None,
    kind: Kind,
    key: str | None,
    language: str | None = None,
) -> str | None:
    family = release_family(release_id)
    if family is None or not key:
        return None
    releases = _installed if _installed is not None else _load(str(NAMES_PATH))
    names = releases.get(family, {}).get(kind, {}).get(key)
    if not names:
        return None
    code = language or current_language()
    return names.get(code) or names.get("en") or names.get("ru")


__all__ = ["NAMES_PATH", "install", "official_name", "release_family"]
