"""S.T.A.L.K.E.R. 2 item knowledge: official names and icons by SID.

``web/s2_items.json`` is generated by ``tools/build_s2_catalog.py`` from the
game's Russian string table (as published by the Russian S.T.A.L.K.E.R.
Wiki), English wiki infoboxes and hand-checked sources.  Presentation only:
nothing here reaches a save writer.
"""

from __future__ import annotations

import json
import re
from functools import cache
from pathlib import Path

from .i18n import current_language

ITEMS_PATH = Path(__file__).resolve().parents[1] / "web" / "s2_items.json"
_installed: dict[str, dict] | None = None


def _items_of(payload: object) -> dict[str, dict]:
    items = payload.get("items") if isinstance(payload, dict) else None
    return items if isinstance(items, dict) else {}


@cache
def _load(path: str) -> dict[str, dict]:
    try:
        return _items_of(json.loads(Path(path).read_text(encoding="utf-8")))
    except (OSError, ValueError):
        return {}


@cache
def _folded(path: str) -> dict[str, str]:
    return {sid.casefold(): sid for sid in _load(path)}


def install(payload: str) -> int:
    """Use the knowledge base fetched by the web page."""

    global _installed
    try:
        _installed = _items_of(json.loads(payload))
    except ValueError:
        _installed = {}
    return len(_installed)


def _items() -> dict[str, dict]:
    return _installed if _installed is not None else _load(str(ITEMS_PATH))


def canonical_sid(sid: str | None) -> str | None:
    """The knowledge-base key for a save SID (``GuardGunX`` → ``GunX``)."""

    value = str(sid or "").strip()
    if not value:
        return None
    items = _items()
    folded = (
        {key.casefold(): key for key in items} if _installed is not None else _folded(str(ITEMS_PATH))
    )
    candidates = [value, re.sub(r"_Player$", "", value)]
    if value.startswith("GuardGun"):
        candidates.append("Gun" + value[len("GuardGun") :])
    for candidate in candidates:
        if candidate in items:
            return candidate
        found = folded.get(candidate.casefold())
        if found:
            return found
    return None


def s2_entry(sid: str | None) -> dict | None:
    key = canonical_sid(sid)
    return _items().get(key) if key else None


def s2_official_name(sid: str | None, language: str | None = None) -> str | None:
    """Official name in the interface language, else English.

    The Russian table is used only for a Russian interface, so other
    languages never show Cyrillic.
    """

    entry = s2_entry(sid)
    if not entry:
        return None
    names = entry.get("names") or {}
    code = language or current_language()
    return names.get(code) or names.get("en")


def s2_description(sid: str | None, language: str | None = None) -> str | None:
    """Official in-game description, by the same rule as the name."""

    entry = s2_entry(sid)
    if not entry:
        return None
    texts = entry.get("descriptions") or {}
    code = language or current_language()
    return texts.get(code) or texts.get("en")


# Items without their own picture borrow one from the same family, so the
# list shows a PDA or a blueprint instead of an empty placeholder.
_FAMILY_ICONS = (
    ("pda", "s2/KozimkovPDA.png"),
    ("blueprint_", "s2/Blueprint_Gvintar_Upgrade_1.png"),
)


def s2_icon_name(sid: str | None) -> str | None:
    entry = s2_entry(sid)
    icon = entry.get("icon") if entry else None
    if icon or not sid:
        return icon
    folded = str(sid).casefold()
    for marker, family_icon in _FAMILY_ICONS:
        if marker in folded:
            return family_icon
    return None


def s2_variant_of(sid: str | None) -> str | None:
    entry = s2_entry(sid)
    return entry.get("variant_of") if entry else None


__all__ = [
    "ITEMS_PATH",
    "canonical_sid",
    "install",
    "s2_description",
    "s2_entry",
    "s2_icon_name",
    "s2_official_name",
    "s2_variant_of",
]
