#!/usr/bin/env python3
"""Export the shared palette so the desktop and browser builds share one source.

`ui/theme.py` owns the colours.  The web build reads them from the generated
`web/theme.css`; regenerating is cheap and `--check` keeps the two from drifting
into "almost the same dark green".
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ui" / "theme.py"
TARGET = ROOT / "web" / "theme.css"
HEADER = (
    "/* Generated by tools/export_theme.py from ui/theme.py - do not edit. */\n"
    ":root {\n"
)


def read_palette() -> dict[str, str]:
    """Read the canonical palette out of ui/theme.py without importing Qt.

    `import ui.theme` pulls in the whole Qt package; a colour export has no
    business requiring PySide6 to be installed.
    """

    tree = ast.parse(SOURCE.read_text(encoding="utf-8"), filename=str(SOURCE))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
        if "PALETTE" not in targets:
            continue
        try:
            value = ast.literal_eval(node.value)
        except (ValueError, TypeError) as exc:
            raise SystemExit("ui/theme.py: PALETTE must be a dict literal") from exc
        if not isinstance(value, dict):
            raise SystemExit("ui/theme.py: PALETTE is not a dict literal")
        return {str(k): str(v) for k, v in value.items()}
    raise SystemExit("ui/theme.py: PALETTE assignment not found")


def render() -> str:
    palette = read_palette()

    lines = [f"  --{name.replace('_', '-')}: {value};" for name, value in palette.items()]
    return HEADER + "\n".join(lines) + "\n}\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered:
            print("web/theme.css is stale; run python3 tools/export_theme.py", file=sys.stderr)
            return 1
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered:
        TARGET.write_text(rendered, encoding="utf-8")
        print(f"updated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
